MasCom.Serverv2/Controllers/UserInfoChangeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MasCom.Serverv2.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class UserInfoChangeController : ControllerBase
    {
        // GET: api/<FileServerController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<FileServerController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<FileServerController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<FileServerController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<FileServerController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

MasCom.Serverv2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace MasCom.Serverv2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MasCom.Serverv2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.IO;
using System.Threading.Tasks;

namespace MasCom.Serverv2.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostDownloadClientAsync()
        {
            var fs = new FileStream("wwwroot/Client.zip", FileMode.Open, FileAccess.Read);
            await Task.CompletedTask;
            return File(fs, "application/zip", "MasComClient.zip");
        }
    }
}

MasCom.Serverv2/Pages/Index.cshtml
@page
@namespace MasCom.Serverv2.Pages
@using MasCom.Serverv2
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IndexModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>MASCOM</title>
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body id="page-top" style="background-image:url(assets/image/bg-masthead.jpg);">
   
    <section class="d-flex masthead" >
        <div class="container my-auto text-center">
            <h1 class="mb-1">MASCOM</h1>
            <h3 class="mb-5"><em>Télécharger le logiciel client</em></h3>
            <form method="post">
                <button type="submit" asp-page-handler="DownloadClient" class="btn btn-primary btn-xl js-scroll-trigger">Télécharger</button>
            </form>
            <div class="overlay"></div>
        </div>
    </section>
</body>

</html>